# Generated by Django 5.2 on 2025-04-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_score', models.FloatField()),
                ('age', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('speeding', models.IntegerField()),
                ('accidents', models.IntegerField()),
                ('severity', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('drunk', models.IntegerField()),
                ('premium', models.FloatField()),
                ('fraud_probability', models.FloatField()),
                ('threshold', models.FloatField()),
                ('prediction', models.CharField(max_length=20)),
                ('payout', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
